parameters:
  twig_cache.adapter.class: highlyprofessionalscum\Twig\CacheExtension\CacheProvider\PsrCacheAdapter
  twig_cache.extension.class: highlyprofessionalscum\Twig\CacheExtension\Extension
  twig_cache.strategy.class: highlyprofessionalscum\Twig\CacheExtension\CacheStrategy\IndexedChainingCacheStrategy
  twig_cache.strategy.generational.class: highlyprofessionalscum\Twig\CacheExtension\CacheStrategy\GenerationalCacheStrategy
  twig_cache.strategy.lifetime.class: highlyprofessionalscum\Twig\CacheExtension\CacheStrategy\LifetimeCacheStrategy
  twig_cache.strategy.spl_object_hash_key_generator.class: highlyprofessionalscum\TwigCacheBundle\KeyGenerator\SplObjectHashKeyGenerator
  twig_cache.default_ttl: 3600

services:
  twig_cache.strategy:
    class: '%twig_cache.strategy.class%'
    public: false
    arguments: [{ gen: '@twig_cache.strategy.generational', time: '@twig_cache.strategy.lifetime' }, '%twig_cache.default_ttl%' ]
  twig_cache.strategy.spl_object_hash_key_generator:
    class: '%twig_cache.strategy.spl_object_hash_key_generator.class%'
    public: false
  twig_cache.adapter:
    class: '%twig_cache.adapter.class%'
    public: false
    arguments: ['@twig_cache.service']
  twig_cache.extension:
    class: '%twig_cache.extension.class%'
    tags:
      - { name: twig.extension }
    arguments: ['@twig_cache.strategy']
  twig_cache.strategy.generational:
    class: '%twig_cache.strategy.generational.class%'
    arguments: ['@twig_cache.adapter', '@twig_cache.strategy.key_generator', '%twig_cache.default_ttl%']
  twig_cache.strategy.lifetime:
    class: '%twig_cache.strategy.lifetime.class%'
    arguments: ['@twig_cache.adapter', '%twig_cache.default_ttl%']
